### ISSUE TITLE
How to use the package for new data？

### ISSUE THREAD

**Issue by db-beep** [duct317/scDHA#5]
new data:hrvatin dataset
demo dataset:goolam dataset
we can see the two datasets(pre-processing) structure is not same.
how to translate the hrvatin to be we can use scDHA process it?
now,we can know the pre-processing is use SingleCellExperiment to make it?

**Comment by db-beep** [comment]
Dear developers,
How to use the new data set on scdha? Can you provide the data preprocessing code？

**Comment by duct317** [comment]
Hi,
Sorry for the late reply. `scDHA` function require a matrix with samples as rows and genes/features as columns. It is recommended to perform log transformation on the matrix if the data range (max - min) is big (e.g. raw count data). Aside from this, we don't really use any preprocessing step when benchmarking our method. 
In case the data is stored in SingleCellExperiment object, you can use this code to get the data matrix
`data <- t(assay(sce))` (transpose needed because the matrix in genes*samples format)
Let me know if you have other questions.
